name: Increment Counter

on:
  schedule:
    - cron: '0 */7 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  increment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Increment counter
        run: |
          count=$(cat counter.txt)
          count=$((count + 1))
          echo "$count" > counter.txt

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add counter.txt
          git commit -m "Update counter to $(cat counter.txt)"
          git push origin HEAD:main
