name: Increment Counter

on:
  schedule:
    - cron: '0 */10 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  increment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Increment counter
        run: |
          count=$(cat counter.txt)
          count=$((count + 1))
          echo "$count" > counter.txt

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add counter.txt

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Counter updated to $(cat counter.txt)"
            git push
          fi
